language: php
env:
  - OC_ROOT=/home/travis/build/vitormattos/opencart-test-suite/www/
  - HTTP_SERVER=http://localhost:8080/
  - TEST_CONFIG=test-config
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.2
install:
  composer install
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - bin/robo opencart:setup
  - bin/phpunit --testsuite catalog-tests
  - bin/phpunit --testsuite admin-tests
